#!/usr/bin/env ruby
# coding: utf-8
require 'yaml'
require 'optparse'
require 'logger'
require 'open-uri'
require_relative 'lib/amazon'

Version = '1.0.0'

class BookInfo
  def initialize
    @log = Logger.new($stderr)
    @log.level = Logger::WARN
  end

  def run
    parse_options

    input = $stdin
    output = $stdout
    attrs = [:isbn, :author, :manufacturer, :title]
    isbn_list = input.read.split.map(&:to_i)

    amazon = Amazon.new(read_config)
    write_header(output, attrs) if @header
    amazon.each_books(isbn_list) do |info|
      @log.info "Book Info Fetched: #{info[:isbn]}"
      write_row(output, attrs, info)
      write_image(info[:isbn], info[:image_uri]) if @image_prefix
    end
  end

  def parse_options
    opt = OptionParser.new
    opt.on('-v', '--verbose', 'Output log') { @log.level = Logger::INFO }
    opt.on('--[no-]header', 'Output header') {|f| @header = f }
    opt.on('--fetch-images=PREFIX', 'Specify image download directory') {|str| @image_prefix = str }
    opt.parse!(ARGV)
  end

  def read_config
    YAML.load(IO.read(File.dirname(__FILE__) + '/config/amazon.yml'))
  end

  def write_header(output, attrs)
    output.puts attrs.join("\t")
  end

  def write_row(output, attrs, info)
    output.puts info.values_at(*attrs).join("\t")
  end

  def write_image(isbn, image_uri)
    open(image_uri) do |image_input|
      image = image_input.read
      image_filename = File.join(@image_prefix, "#{isbn}#{File.extname(image_uri)}")
      open(image_filename, 'wb') do |image_output|
        @log.info "Image Fetched: #{image_uri}"
        image_output.write(image)
      end
    end
  end
end

BookInfo.new.run
